// src/app/common/nav-bar/nav-bar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RegisterComponent } from '../register/register.component';

@Component({
  selector: 'app-nav-bar',
  standalone: true,
  imports: [CommonModule, RegisterComponent],
  templateUrl: './nav-bar.component.html',
  styleUrl: './nav-bar.component.css'
})
export class NavBarComponent {

  isRegisterPopupVisible = false;
  
  openRegisterPopup(): void {
    console.log('Register button clicked');
    this.isRegisterPopupVisible = true;
  }
  
  closeRegisterPopup(): void {
    this.isRegisterPopupVisible = false;
    console.log(this.isRegisterPopupVisible);
    
  }
  
  openLoginPopup(): void {
    console.log('Sign in button clicked');
    this.isRegisterPopupVisible = false;
    console.log(this.isRegisterPopupVisible);
  }
}

<nav class="navbar">
    <div class="navbar-container">
        <div class="logo">
            Even<span class="logo-accent">ticks</span>
        </div>

        <div class="hamburger" id="hamburger">
            <span></span>
            <span></span>
            <span></span>
        </div>

        <ul class="nav-links" id="navLinks">
            <li class="dropdown-container">
                <a href="#" class="dropdown-toggle">
                    Events
                    <svg class="dropdown-arrow" xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <polyline points="6 9 12 15 18 9"></polyline>
                    </svg>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="#">Concerts</a>
                    </li>
                    <li>
                        <a href="#">Festivals</a>
                    </li>
                    <li>
                        <a href="#">Workshops</a>
                    </li>
                </ul>
            </li>
            <li class="dropdown-container">
                <a href="#" class="dropdown-toggle">
                    Theater
                    <svg class="dropdown-arrow" xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <polyline points="6 9 12 15 18 9"></polyline>
                    </svg>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="#">Drama</a>
                    </li>
                    <li>
                        <a href="#">Musicals</a>
                    </li>
                    <li>
                        <a href="#">Comedy</a>
                    </li>
                </ul>
            </li>
            <li class="dropdown-container">
                <a href="#" class="dropdown-toggle">
                    Sports
                    <svg class="dropdown-arrow" xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <polyline points="6 9 12 15 18 9"></polyline>
                    </svg>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="#">Football</a>
                    </li>
                    <li>
                        <a href="#">Basketball</a>
                    </li>
                    <li>
                        <a href="#">Tennis</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">Leisure</a>
            </li>
            <li>
                <a href="#">Other</a>
            </li>
            
            <!-- Mobile auth options -->
            <li class="mobile-auth-item" *ngIf="!isLoggedIn">
                <button class="sign-in-btn mobile" (click)="openLogin()">Sign In</button>
                <button class="register-btn mobile" (click)="openRegister()">Register</button>
            </li>
            <li class="mobile-auth-item" *ngIf="isLoggedIn">
                <div class="user-info-mobile">
                    <span class="username-label">Hello, {{ userName }}</span>
                    <a href="#" class="mobile-account-link">My Account</a>
                    <a href="#" class="mobile-logout-link" (click)="logout()">Logout</a>
                </div>
            </li>
        </ul>

        <div class="auth-buttons desktop">
            <ng-container *ngIf="!isLoggedIn">
                <button class="register-btn" routerLink="" (click)="openRegister()">Register</button>
                <button class="sign-in-btn" (click)="openLogin()">Sign In</button>
            </ng-container>
            
            <ng-container *ngIf="isLoggedIn">
                <div class="dropdown-container user-dropdown">
                    <a href="#" class="dropdown-toggle user-menu-btn">
                        <span class="user-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                <circle cx="12" cy="7" r="4"></circle>
                            </svg>
                        </span>
                        {{ userName }}
                        <svg class="dropdown-arrow" xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                            viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                            stroke-linejoin="round">
                            <polyline points="6 9 12 15 18 9"></polyline>
                        </svg>
                    </a>
                    <ul class="dropdown-menu user-dropdown-menu">
                        <li>
                            <a href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                    <circle cx="12" cy="7" r="4"></circle>
                                </svg>
                                My Account
                            </a>
                        </li>
                        <li>
                            <a href="#" (click)="logout()">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                                    <polyline points="16 17 21 12 16 7"></polyline>
                                    <line x1="21" y1="12" x2="9" y2="12"></line>
                                </svg>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </ng-container>
        </div>
        
    </div>
</nav>

<div class="content-container">

</div>

<app-register *ngIf="showRegister" (close)="closeRegister()" (login)="handleGoToLogin()">
</app-register>

<app-login *ngIf="showLogin" (close)="closeLogin()" (register)="handleGoToRegister()"
    (forgotPassword)="handleGoToForgotPassword($event)">
</app-login>

<app-forgot-password *ngIf="showForgotPassword" [email]="userEmail" (close)="closeForgotPassword()"
    (login)="handleBackToLogin()">
</app-forgot-password>

// src/components/NavBar.jsx
import React, { useState } from "react";
import "./navbar.css";

export default function NavBar() {
  const [dropdown, setDropdown] = useState(null);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  const toggleDropdown = (menu) => {
    setDropdown(dropdown === menu ? null : menu);
  };

  const toggleMobileMenu = () => {
    setIsMobileMenuOpen(!isMobileMenuOpen);
  };

  return (
    <nav className="navbar">
      <div className="navbar-container">
        <div className="logo">
          Even<span className="logo-accent">ticks</span>
        </div>

        <div
          className={`hamburger ${isMobileMenuOpen ? "active" : ""}`}
          onClick={toggleMobileMenu}
        >
          <span></span>
          <span></span>
          <span></span>
        </div>

        <ul className={`nav-links ${isMobileMenuOpen ? "active" : ""}`}>
          <li
            className="dropdown-container"
            onMouseEnter={() => toggleDropdown("events")}
            onMouseLeave={() => setDropdown(null)}
          >
            <a href="#" className="dropdown-toggle">
              Events
              <svg
                className="dropdown-arrow"
                xmlns="http://www.w3.org/2000/svg"
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </a>
            {dropdown === "events" && (
              <ul className="dropdown-menu">
                <li>
                  <a href="#">Concerts</a>
                </li>
                <li>
                  <a href="#">Festivals</a>
                </li>
                <li>
                  <a href="#">Workshops</a>
                </li>
              </ul>
            )}
          </li>
          <li
            className="dropdown-container"
            onMouseEnter={() => toggleDropdown("theater")}
            onMouseLeave={() => setDropdown(null)}
          >
            <a href="#" className="dropdown-toggle">
              Theater
              <svg
                className="dropdown-arrow"
                xmlns="http://www.w3.org/2000/svg"
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </a>
            {dropdown === "theater" && (
              <ul className="dropdown-menu">
                <li>
                  <a href="#">Drama</a>
                </li>
                <li>
                  <a href="#">Musicals</a>
                </li>
                <li>
                  <a href="#">Comedy</a>
                </li>
              </ul>
            )}
          </li>
          <li
            className="dropdown-container"
            onMouseEnter={() => toggleDropdown("sports")}
            onMouseLeave={() => setDropdown(null)}
          >
            <a href="#" className="dropdown-toggle">
              Sports
              <svg
                className="dropdown-arrow"
                xmlns="http://www.w3.org/2000/svg"
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </a>
            {dropdown === "sports" && (
              <ul className="dropdown-menu">
                <li>
                  <a href="#">Football</a>
                </li>
                <li>
                  <a href="#">Basketball</a>
                </li>
                <li>
                  <a href="#">Tennis</a>
                </li>
              </ul>
            )}
          </li>
          <li>
            <a href="#">Leisure</a>
          </li>
          <li>
            <a href="#">Other</a>
          </li>
        </ul>
        <div className="auth-buttons desktop">
          <button className="register-btn">Register</button>
          <button className="sign-in-btn">Sign In</button>
        </div>
      </div>
    </nav>
  );
}
