// src/app/components/nav-bar/nav-bar.component.ts
import { Component, ViewChild, AfterViewInit, HostListener, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RegisterComponent } from '../register/register.component';
import { LoginComponent } from '../login/login.component';
import { ForgotPasswordComponent } from '../forgot-password/forgot-password.component';
import { AuthService } from '../../services/auth.service';
import { Subscription } from 'rxjs';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-nav-bar',
  standalone: true,
  imports: [CommonModule, RegisterComponent, LoginComponent, ForgotPasswordComponent, RouterLink],
  templateUrl: './nav-bar.component.html',
  styleUrl: './nav-bar.component.css'
})
export class NavBarComponent implements AfterViewInit, OnInit, OnDestroy {
  showRegister = false;
  showLogin = false;
  showForgotPassword = false;
  isLoggedIn = false;
  userName = 'User';
  userEmail = '';
  isScrolled = false;
  isMemorySession = false;
  private authSubscription: Subscription | null = null;

  @ViewChild(RegisterComponent) registerComponent!: RegisterComponent;
  @ViewChild(LoginComponent) loginComponent!: LoginComponent;
  @ViewChild(ForgotPasswordComponent) forgotPasswordComponent!: ForgotPasswordComponent;

  constructor(private authService: AuthService) {}

  ngOnInit(): void {
    this.authSubscription = this.authService.currentUser$.subscribe(user => {
      this.isLoggedIn = !!user;
      if (user) {
        this.userName = user.name || user.username || user.email || 'User';
        this.userEmail = user.email || '';
        this.isMemorySession = this.authService.isInMemoryOnly();
      } else {
        this.userName = 'User';
        this.userEmail = '';
        this.isMemorySession = false;
      }
    });
    
    this.checkAuthStatus();
  }

  ngOnDestroy(): void {
    if (this.authSubscription) {
      this.authSubscription.unsubscribe();
    }
  }

  ngAfterViewInit(): void {
    this.initMobileMenu();
  }

  @HostListener('window:scroll', [])
  onWindowScroll() {
    this.isScrolled = window.scrollY > 20;
    const navbar = document.querySelector('.navbar');
    if (navbar) {
      if (this.isScrolled) {
        navbar.classList.add('scrolled');
      } else {
        navbar.classList.remove('scrolled');
      }
    }
  }

  @HostListener('window:beforeunload', ['$event'])
  checkMemorySession(event: BeforeUnloadEvent) {
    if (this.isLoggedIn && this.isMemorySession) {
      const message = 'Your login session is not saved and will be lost when you close the window.';
      event.returnValue = message;
      return message;
    }
    return null;
  }

  checkAuthStatus(): void {
    const user = this.authService.getCurrentUser();
    
    if (user) {
      this.isLoggedIn = !!user.token;
      this.userName = user.name || user.username || user.email || 'User';
      this.userEmail = user.email || '';
      this.isMemorySession = this.authService.isInMemoryOnly();
    } else {
      this.isLoggedIn = false;
      this.userName = 'User';
      this.userEmail = '';
      this.isMemorySession = false;
    }
  }

  logout(): void {
    this.authService.logout();
    this.isLoggedIn = false;
    this.userName = 'User';
    this.userEmail = '';
    this.isMemorySession = false;
    this.closeMenu();
  }

  openRegister(): void {
    this.showRegister = true;
    this.closeMenu();
    setTimeout(() => {
      if (this.registerComponent) {
        this.registerComponent.openModal();
      }
    });
  }

  closeRegister(): void {
    this.showRegister = false;
    this.checkAuthStatus();
  }

  openLogin(): void {
    this.showLogin = true;
    this.closeMenu();
    setTimeout(() => {
      if (this.loginComponent) {
        this.loginComponent.openModal();
      }
    });
  }

  closeLogin(): void {
    this.showLogin = false;
    this.checkAuthStatus();
  }

  handleGoToForgotPassword(email: string): void {
    this.userEmail = email;
    this.showLogin = false;

    setTimeout(() => {
      this.showForgotPassword = true;

      setTimeout(() => {
        if (this.forgotPasswordComponent) {
          this.forgotPasswordComponent.email = this.userEmail;
          this.forgotPasswordComponent.openModal();
        }
      });
    }, 300);
  }

  closeForgotPassword(): void {
    this.showForgotPassword = false;
  }

  handleGoToLogin(): void {
    if (this.showRegister) {
      this.showRegister = false;
    } else if (this.showForgotPassword) {
      this.showForgotPassword = false;
    }

    setTimeout(() => {
      this.showLogin = true;

      setTimeout(() => {
        if (this.loginComponent) {
          this.loginComponent.openModal();
        }
      });
    }, 300);
  }

  handleBackToLogin(): void {
    this.handleGoToLogin();
  }

  handleGoToRegister(): void {
    this.showLogin = false;

    setTimeout(() => {
      this.showRegister = true;

      setTimeout(() => {
        if (this.registerComponent) {
          this.registerComponent.openModal();
        }
      });
    }, 300);
  }
  getSessionType(): string {
    if (!this.isLoggedIn) return '';
    return this.isMemorySession ? 
      'Session (will expire when browser closes)' : 
      'Persistent login';
  }

  private closeMenu(): void {
    const hamburger = document.getElementById('hamburger');
    const navLinks = document.getElementById('navLinks');

    if (hamburger && navLinks) {
      hamburger.classList.remove('active');
      navLinks.classList.remove('active');
      document.body.classList.remove('menu-open');
    }
  }

  private initMobileMenu(): void {
    const hamburger = document.getElementById('hamburger');
    const navLinks = document.getElementById('navLinks');

    if (hamburger && navLinks) {
      hamburger.addEventListener('click', () => {
        navLinks.classList.toggle('active');
        hamburger.classList.toggle('active');
        document.body.classList.toggle('menu-open');
      });
    }

    document.addEventListener('click', (event) => {
      const target = event.target as HTMLElement;
      const hamburgerBtn = document.getElementById('hamburger');
      const menu = document.getElementById('navLinks');

      if (
        menu &&
        hamburgerBtn &&
        menu.classList.contains('active') &&
        !menu.contains(target) &&
        !hamburgerBtn.contains(target)
      ) {
        this.closeMenu();
      }
    });

    const dropdownToggles = document.querySelectorAll('.dropdown-toggle');
    dropdownToggles.forEach(toggle => {
      toggle.addEventListener('click', (e) => {
        if (window.innerWidth <= 768) {
          e.preventDefault();
          const parent = (toggle as HTMLElement).closest('.dropdown-container');

          const allDropdowns = document.querySelectorAll('.dropdown-container.active');
          allDropdowns.forEach(dropdown => {
            if (dropdown !== parent) {
              dropdown.classList.remove('active');
            }
          });

          parent?.classList.toggle('active');
        }
      });
    });

    window.addEventListener('resize', () => {
      if (window.innerWidth > 768) {
        this.closeMenu();

        const activeDropdowns = document.querySelectorAll('.dropdown-container.active');
        activeDropdowns.forEach(dropdown => {
          dropdown.classList.remove('active');
        });
      }
    });
  }
}
<nav class="navbar">
    <div class="navbar-container">
        <div class="logo" routerLink="/">
            Even<span class="logo-accent">ticks</span>
        </div>

        <div class="hamburger" id="hamburger">
            <span></span>
            <span></span>
            <span></span>
        </div>

        <ul class="nav-links" id="navLinks">
            <li class="dropdown-container">
                <a href="#" class="dropdown-toggle">
                    Events
                    <svg class="dropdown-arrow" xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <polyline points="6 9 12 15 18 9"></polyline>
                    </svg>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="#">Concerts</a>
                    </li>
                    <li>
                        <a href="#">Festivals</a>
                    </li>
                    <li>
                        <a href="#">Workshops</a>
                    </li>
                </ul>
            </li>
            <li class="dropdown-container">
                <a href="#" class="dropdown-toggle">
                    Theater
                    <svg class="dropdown-arrow" xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <polyline points="6 9 12 15 18 9"></polyline>
                    </svg>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="#">Drama</a>
                    </li>
                    <li>
                        <a href="#">Musicals</a>
                    </li>
                    <li>
                        <a href="#">Comedy</a>
                    </li>
                </ul>
            </li>
            <li class="dropdown-container">
                <a href="#" class="dropdown-toggle">
                    Sports
                    <svg class="dropdown-arrow" xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <polyline points="6 9 12 15 18 9"></polyline>
                    </svg>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="#">Football</a>
                    </li>
                    <li>
                        <a href="#">Basketball</a>
                    </li>
                    <li>
                        <a href="#">Tennis</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">Leisure</a>
            </li>
            <li>
                <a href="#">Other</a>
            </li>
            
            <!-- Mobile auth options -->
            <li class="mobile-auth-item" *ngIf="!isLoggedIn">
                <button class="sign-in-btn mobile" (click)="openLogin()">Sign In</button>
                <button class="register-btn mobile" (click)="openRegister()">Register</button>
            </li>
            <li class="mobile-auth-item" *ngIf="isLoggedIn">
                <div class="user-info-mobile">
                    <span class="username-label">Hello, {{ userName }}</span>
                    <a class="mobile-account-link" routerLink="/user-profile">My Account</a>
                    <a href="#" class="mobile-logout-link" (click)="logout()">Logout</a>
                </div>
            </li>
        </ul>

        <div class="auth-buttons desktop">
            <ng-container *ngIf="!isLoggedIn">
                <button class="register-btn" routerLink="" (click)="openRegister()">Register</button>
                <button class="sign-in-btn" (click)="openLogin()">Sign In</button>
            </ng-container>
            
            <ng-container *ngIf="isLoggedIn">
                <div class="dropdown-container user-dropdown">
                    <a href="#" class="dropdown-toggle user-menu-btn">
                        <span class="user-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                <circle cx="12" cy="7" r="4"></circle>
                            </svg>
                        </span>
                        {{ userName }}
                        <svg class="dropdown-arrow" xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                            viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                            stroke-linejoin="round">
                            <polyline points="6 9 12 15 18 9"></polyline>
                        </svg>
                    </a>
                    <ul class="dropdown-menu user-dropdown-menu">
                        <li>
                            <a routerLink="/profile">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                    <circle cx="12" cy="7" r="4"></circle>
                                </svg>
                                My Account
                            </a>
                        </li>
                        <li>
                            <a href="#" (click)="logout()">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                                    <polyline points="16 17 21 12 16 7"></polyline>
                                    <line x1="21" y1="12" x2="9" y2="12"></line>
                                </svg>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </ng-container>
        </div>
        
    </div>
</nav>

<div class="content-container">

</div>

<app-register *ngIf="showRegister" (close)="closeRegister()" (login)="handleGoToLogin()">
</app-register>

<app-login *ngIf="showLogin" (close)="closeLogin()" (register)="handleGoToRegister()"
    (forgotPassword)="handleGoToForgotPassword($event)">
</app-login>

<app-forgot-password *ngIf="showForgotPassword" [email]="userEmail" (close)="closeForgotPassword()"
    (login)="handleBackToLogin()">
</app-forgot-password>

// src/components/NavBar.jsx
import React, { useState } from "react";
import "./navbar.css";

export default function NavBar() {
  const [dropdown, setDropdown] = useState(null);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  const toggleDropdown = (menu) => {
    setDropdown(dropdown === menu ? null : menu);
  };

  const toggleMobileMenu = () => {
    setIsMobileMenuOpen(!isMobileMenuOpen);
  };

  return (
    <nav className="navbar">
      <div className="navbar-container">
        <div className="logo">
          Even<span className="logo-accent">ticks</span>
        </div>

        <div
          className={`hamburger ${isMobileMenuOpen ? "active" : ""}`}
          onClick={toggleMobileMenu}
        >
          <span></span>
          <span></span>
          <span></span>
        </div>

        <ul className={`nav-links ${isMobileMenuOpen ? "active" : ""}`}>
          <li
            className="dropdown-container"
            onMouseEnter={() => toggleDropdown("events")}
            onMouseLeave={() => setDropdown(null)}
          >
            <a href="#" className="dropdown-toggle">
              Events
              <svg
                className="dropdown-arrow"
                xmlns="http://www.w3.org/2000/svg"
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </a>
            {dropdown === "events" && (
              <ul className="dropdown-menu">
                <li>
                  <a href="#">Concerts</a>
                </li>
                <li>
                  <a href="#">Festivals</a>
                </li>
                <li>
                  <a href="#">Workshops</a>
                </li>
              </ul>
            )}
          </li>
          <li
            className="dropdown-container"
            onMouseEnter={() => toggleDropdown("theater")}
            onMouseLeave={() => setDropdown(null)}
          >
            <a href="#" className="dropdown-toggle">
              Theater
              <svg
                className="dropdown-arrow"
                xmlns="http://www.w3.org/2000/svg"
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </a>
            {dropdown === "theater" && (
              <ul className="dropdown-menu">
                <li>
                  <a href="#">Drama</a>
                </li>
                <li>
                  <a href="#">Musicals</a>
                </li>
                <li>
                  <a href="#">Comedy</a>
                </li>
              </ul>
            )}
          </li>
          <li
            className="dropdown-container"
            onMouseEnter={() => toggleDropdown("sports")}
            onMouseLeave={() => setDropdown(null)}
          >
            <a href="#" className="dropdown-toggle">
              Sports
              <svg
                className="dropdown-arrow"
                xmlns="http://www.w3.org/2000/svg"
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </a>
            {dropdown === "sports" && (
              <ul className="dropdown-menu">
                <li>
                  <a href="#">Football</a>
                </li>
                <li>
                  <a href="#">Basketball</a>
                </li>
                <li>
                  <a href="#">Tennis</a>
                </li>
              </ul>
            )}
          </li>
          <li>
            <a href="#">Leisure</a>
          </li>
          <li>
            <a href="#">Other</a>
          </li>
        </ul>
        <div className="auth-buttons desktop">
          <button className="register-btn">Register</button>
          <button className="sign-in-btn">Sign In</button>
        </div>
      </div>
    </nav>
  );
}
